name: Deploy Backend (Docker Compose)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/BloggIt-Backend

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping containers..."
            docker compose docker-compose.yaml down
            
            docker system prune -a -f
            echo "Starting containers..."
            docker compose -f docker-compose.yaml up -d --build --remove-orphans